### PR TITLE
Fix spelling of "don't"

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by stephennancekivell** [comment]
Is this spam ? Are you a human @waldyrious

**Comment by waldyrious** [comment]
Huh? Why do you ask? :(

**Comment by stephennancekivell** [comment]
I only ask because this and some of your other PR's look automated.

Anyway, regarding this PR. Can you correct the punctuation in program not just the example in the readme. Thanks.

**Comment by waldyrious** [comment]
Please let me know a couple examples of other PRs that look automated. I definitely didn't want to give out that impression. And in this particular case, what would have made it look less automated? Perhaps a description in the PR? I normally don't add one for simple fixes like this because the commit message / PR title already conveys all the information, but I understand if that doesn't sound sufficient to others.

As for the changes you requested, sure, I'll do it now.

**Comment by stephennancekivell** [comment]
Thanks. 

I just thought there might be a bot looking for spelling mistakes.

**Comment by waldyrious** [comment]
Ok, thanks for the clarification. Out of curiosity, if there was indeed a bot that provided small fixes like this, would you consider that spam and not merge the PR? If so, I'd be interested in understanding your perspective (after all, it would still be an improvement, even if a small one).

**Pull request merged**
